### ISSUE TITLE
Problems when I use a large image as source

### ISSUE THREAD

**Issue by Ingolmo** [maxime-tremblay/apex-plugin-imagecropper#1]
Hi there,

I created an app including this dynamic action plugin, where I insert the cropped image as a blob column. If I use for that a small photo, I haven't any issue, but when I use a large image as source (1920x1080, for example), then the action is performed but need to refresh the page after the sumbit action in order to display the new croped image. That doesn't happen when I use a smaller image.

The secuence, to clarify a bit more, is I call the plugin in a page, set the image and after submit I fetch rows from that table at a different page. The redirect, submit, etc actions work propperly when I use a small image as source, but if I use a large one, the new cropped image does not display until I refresh that page.

Any idea why is this happening? Any help would be much appreciated.

**Comment by maxime-tremblay** [comment]
What happens is that the submit is not waiting for the cropping pl/sql process to be completed.

You need to set the save button action to "defined by dynamic action" and if not done already 
define a static id for that button (which you'll use in the plugin attributes under "Save Button jQuery Selector").

Then you'll need to define a dynamic action that will be triggered once the save process completes.
From readme

> Cropper Save Done
> - Event: `Cropped Image Save to DB`
> - Selection Type: `JavaScript Expression`
> - JavaScript Expression: `document`
> - True Action
>   - Action: `Submit Page`
>   - Request/Button Name: `SAVE`

I also updated the Readme because it did not mention to set the save button action to "defined by dynamic action".

**Comment by Ingolmo** [comment]
Thanks a lot!! Now is working propperly!! 

Thanks for the great plugin, and quick answer!!
